[build]
  # Build command for Astro
  command = "npm run build"
  
  # Directory where the built files will be located
  # Astro builds to 'dist' by default
  publish = "dist"

[build.environment]
  # Node.js version - using LTS version for stability
  NODE_VERSION = "20"
  
  # Enable npm ci for faster, reliable builds
  NPM_FLAGS = "--production=false"
  
  # Ensure consistent package resolution between pnpm and npm
  NODE_OPTIONS = "--max-old-space-size=4096"

# Redirect rules for SPA-like behavior (if needed)
[[redirects]]
  # Handle client-side routing for any missing pages
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache static assets for better performance
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.html"
  [headers.values]
    # Cache HTML files for a shorter time
    Cache-Control = "public, max-age=0, must-revalidate"

# Functions (if you plan to use Netlify Functions)
[functions]
  # Directory for Netlify Functions
  directory = "netlify/functions"

# Edge Functions (if you plan to use Netlify Edge Functions)
[edge_functions]
  # Directory for Edge Functions
  directory = "netlify/edge-functions"

# Plugin configuration (if using Netlify plugins)
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
  [plugins.inputs.thresholds]
    performance = 0.9
    accessibility = 0.9
    best-practices = 0.9
    seo = 0.9

# Branch-specific settings
[context.production]
  command = "npm run build"
  publish = "dist"

[context.deploy-preview]
  command = "npm run build"
  publish = "dist"

[context.branch-deploy]
  command = "npm run build"
  publish = "dist"
